### ISSUE TITLE
最新版好像......干净利落地崩了?

### ISSUE THREAD

**Issue by XZYawa** [ukmojb/The-One-Probe-Community-Edition#16]
mod仅有TheOneProbe-CE-1.12-1.3.0
java是LibericaJDK1.8.0_412
日志:
[latest.log](https://github.com/user-attachments/files/17444645/latest.log)

**Comment by ukmojb** [comment]
没事，正在修，还有1.3.0弄成阿尔法版本了

**Comment by XZYawa** [comment]
> 没事，正在修，还有1.3.0弄成阿尔法版本了

ok
感谢大佬!

**Comment by ukmojb** [comment]
再试试，应该只是打包错误

**Comment by ukmojb** [comment]
还有新模组出了
https://www.curseforge.com/minecraft/mc-mods/topalldependents

**Comment by XZYawa** [comment]
> 再试试，应该只是打包错误

确实没问题啦
新mod已装,多谢~
