### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by mczph** [ukmojb/The-One-Probe-Community-Edition#2]
1.合并余烬高亮支持Ember Top and Waila
https://www.mcmod.cn/class/3990.html
2.添加对植物魔法魔力的支持

**Comment by ukmojb** [comment]
魔力显示已经有了

**Comment by mczph** [comment]
啊，是CE的功能吗，我这里没有

**Comment by mczph** [comment]
另外你说的是额外植物学的吧，我其实想要那种条子的，就像电量的显示一样

**Comment by ukmojb** [comment]
余烬高亮已合并
