### ISSUE TITLE
Error: theoneprobe:default

### ISSUE THREAD

**Issue by ZHAY10086** [ukmojb/The-One-Probe-Community-Edition#5]
安装TOPCE后，出现如下提示：
![1682426912_361656_yuNN](https://user-images.githubusercontent.com/34602681/234286645-a3265142-bc61-4929-93ab-fe9554fb5c90.png)
经测试，非其他mod冲突导致，仅安装TOPCE同样会出现该情况。
补充：1.1.1版本无此问题，为1.1.2版本新增的bug

**Comment by ukmojb** [comment]
已修复
