### ISSUE TITLE
Divine Journey 2 服务端不兼容 & 一些小问题

### ISSUE THREAD

**Issue by ZHAY10086** [ukmojb/The-One-Probe-Community-Edition#6]
整合包：Divine Journey 2 2.19.3

TOPML版本：1.1.5

问题：客户端可以正常启动，但服务端会出现如下错误报告：
https://pastebin.com/Hfdmhjdv

**Comment by ZHAY10086** [comment]
另：`shovel`在游戏中对应的称呼是`锹`，而不是`铲`

**Comment by ukmojb** [comment]
解决
