### ISSUE TITLE
Error:theoneprobe:default with ArchitectureCraft

### ISSUE THREAD

**Issue by Routersan** [ukmojb/The-One-Probe-Community-Edition#8]
Nihao!
If I look at any blocks made in ArchitectureCraft's sawbench, then TOP shows Error:theoneprobe:default
Can you correct this?
Used mods:
TheOneProbe-CE-1.12-1.2.0
architecturecraft-1.12-3.108
Thank you!

**Comment by ukmojb** [comment]
Could you please send out the curseforge link for it
I'm not sure if this is it(https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev)

**Comment by ukmojb** [comment]
![2023-12-09_08 53 53](https://github.com/ukmojb/The-One-Probe-Community-Edition/assets/105061290/34e0a34e-a714-446c-b6ca-bf5bd43c0310)
My side is normal, why don't you update to 1.2.2?

**Comment by ukmojb** [comment]
Or you can send out a list of mods

**Comment by Routersan** [comment]
Thanks for your reply! I am update on 1.2.4 but the problem is still there. 
![2](https://github.com/ukmojb/The-One-Probe-Community-Edition/assets/148059703/ae2f1cd8-f4df-4a31-8f30-8723b2cd5609)
![3](https://github.com/ukmojb/The-One-Probe-Community-Edition/assets/148059703/7e6b4366-d3f6-4464-9e01-760b578a4a56)
I use Russian language.

**Comment by Routersan** [comment]
Modlist from my pack:

!configanytime-1.0.jar
!mixinbooter-8.8.jar
AbyssalCraft+Integration-1.12.2-1.11.3.jar
AbyssalCraft-1.12.2-1.10.5.jar
Aether+Continuation+v1.3.0.jar
aether-1.12.2-v1.5.3.2.jar
alchemistry-1.12.2-42.jar
alib-1.0.12.jar
AncientSpellcraft-1.12.2-1.5.10.jar
ancientwarfare-1.12.2-2.9.1.unstable.jar
AppleSkin-mc1.12-1.0.14.jar
arcane_essentials-1.0.1.jar
architecturecraft-1.12-3.108.jar
ArtemisLib-1.12.2-v1.0.6.jar
Atum-1.12.2-2.0.20.jar
AutoRegLib-1.3-32.jar
Avaritia-1.12.2-3.3.0.37-universal.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
beebetteratbees-1.12.2-2.0.3.jar
BetterAdvancements-1.12.2-0.1.0.77.jar
betterbiomeblend-1.12.2-1.1.7-forge.jar
BetterMineshaftsForge-1.12.2-2.2.1.jar
betternether-0.1.8.6.jar
BetterQuestingUnofficial-4.1.0.jar
BiblioCraft[v2.4.6][MC1.12.2].jar
binnie-mods-1.12.2-2.5.1.211.jar
BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
blockcraftery-1.12.2-1.3.1.jar
Bloodmoon-MC1.12.2-1.5.3.jar
bogosorter-1.4.5.jar
bonsaitrees-1.1.4-b170.jar
Bookshelf-1.12.2-2.3.590.jar
Botania+r1.10-364.4.jar
BrandonsCore-1.12.2-2.4.20.162-universal.jar
BringMeTheRings-0.4.jar
BuildingGadgets-2.8.4.jar
camera-1.0.11.jar
carryon-1.12.2-1.12.6.20.jar
CD4017BE_lib-1.12.2-6.5.1.jar
censoredasm5.18.jar
Chameleon-1.12-4.1.3.jar
Charm-1.12.2-1.4.1.jar
ChineseWorkshop-1.12.2_1.2.6.jar
Chisel-MC1.12.2-1.0.2.45.jar
Chocolate_Quest_Repoured-1.12.2-2.6.16B.jar
chunkloaders-1.2.3-forge-mc1.12.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
collective-1.12.2-3.0.jar
comforts-1.12.2-1.4.1.3.jar
conarm-1.12.2-1.2.5.10.jar
ContainerFix+MC1.12.2+v1.0.jar
Controlling-3.0.12.2.jar
CookingForBlockheads_1.12.2-6.5.0.jar
CraftingTweaks_1.12.2-8.1.9.jar
crimsonwarfare-1.5.jar
cta-1.12.2-1.2.1.jar
CTM-MC1.12.2-1.0.2.31.jar
DankNull-1.12.2-1.7.101.jar
davincisvessels-1.12-6.355-full.jar
DimensionalDoors-1.12.2-3.0.12.jar
DoomlikeDungeons-1.14.12-MC1.12.2.jar
Draconic-Additions-1.12.2-1.17.0.45-universal.jar
Draconic-Evolution-1.12.2-2.3.28.354-universal.jar
draw_bridge-1.12.2-1.2.1.8.jar
DrZharks-MoCreatures-Extended-12.3.1.jar
DummyCoreUnofficial-2.4.112.5.jar
DungeonMobs-5.8.10-MC1.12.2.jar
Dungeons2-mc1.12.2-f14.23.5.2859-v1.7.6.jar
DynamicSurroundings-1.12.2-3.6.2.1.jar
DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar
ElectroblobsWizardry-4.3.11.jar
elegant-networking-1.12-3.16.jar
EnchantingPlusPlus-1.12.2-5.1.0.jar
endercompass-1.5.1-1.12.2.jar
EnderStorage-1.12.2-2.4.6.137-universal.jar
EndReborn+[0.3.9].jar
engineers_doors-1.12.2-0.9.1.jar
engineersdecor-1.12.2-1.1.4.jar
engineerstools-1.12.2-1.0.5.jar
EntityCulling-1.12.2-6.4.2.jar
extraalchemy-forge-1.12-build11-0.5.4.jar
ExtraBotany-r1.1-60-beta-hotfix.jar
ExtraPlanets-1.12.2-0.7.7.jar
extrautils2-1.12-1.9.9.jar
eyeofdragons-0.0.2.jar
FarmingForBlockheads_1.12.2-3.1.28.jar
Fish's+Undead+Rising-1.4.0.jar
FluxNetworks-1.12.2-4.1.1.34.jar
forestry_1.12.2-5.8.2.422.jar
Forgelin-1.8.4.jar
fossilsarcheology-8.0.6.jar
FpsReducer-mc1.12.2-1.20.jar
FTBBackups-1.1.0.1.jar
furniture-6.3.2-1.12.2.jar
Galacticraft-1.12.2-4.0.6.jar
geckolib-forge-1.12.2-3.0.29.jar
gendustry-1.6.5.8-mc1.12.2.jar
gendustryjei-1.0.2.jar
gogredux-1.12.2-1.0.0.jar
GottschCore-mc1.12.2-f14.23.5.2859-v1.15.0.jar
GrimoireOfGaia3-1.12.2-1.7.2.jar
Guidebook-1.12.2-2.9.5.jar
GunpowderLib-1.12.2-1.1.jar
HadEnoughItems_1.12.2-4.25.1.jar
HammerLib-1.12.2-2.0.6.32.jar
Headcrumbs-1.12.2-2.0.5.17.jar
iceandfire-1.9.1-1.12.2.jar
ImmersiveEngineering-0.12-98.jar
immersivepetroleum-1.12.2-1.1.10.jar
ImmersivePosts-0.2.1.jar
InductiveLogistics-1.12.2-1.3.5.jar
industrialforegoing-1.12.2-1.12.13-237.jar
infinitetrading_1.12.2-1.4.jar
instantunify-1.12.2-1.1.2.jar
IntegrationForegoing-1.12.2-1.11.jar
invisiblights-3.2-10.jar
ironchest-1.12.2-7.0.72.847.jar
ironfurnaces-1.3.5.jar
isorropia-1.12.2-0.1.14.jar
jeibees-0.9.0.5-mc1.12.2.jar
jeiintegration_1.12.2-1.6.0.jar
jeivillagers-1.12-1.0.2.jar
jepb-1.12-1.2.1.jar
JustEnoughPetroleum-0.1.jar
JustEnoughResources-1.12.2-0.9.3.203.jar
KeepingInventory-1.12.2-2.4.jar
Kiwi-1.12.2-0.5.3.32.jar
LagGoggles-1.12.2-5.8-132.jar
Leshen-1.2.jar
LibraryEx-1.12.2-1.2.2.jar
llibrary-1.7.20-1.12.2.jar
lost-aether-content-1.12.2-1.0.2.jar
lostcities-1.12-2.0.22.jar
ltta-1.12.2-1.4.0.jar
MagicBees-1.12.2-3.2.25.jar
Mantle-1.12-1.3.3.55.jar
MCTImmersiveTechnology-1.12.2-1.9.101.jar
mcw-bridges-1.0.6b-mc1.12.2.jar
mcw-doors-1.0.3-mc1.12.2.jar
mcw-fences-1.0.0-mc1.12.2.jar
mcw-roofs-1.0.2-mc1.12.2.jar
mcw_paintings-1.0.4-mc1.12.2.jar
medivalmusic-1.1.jar
Millenaire+Extended-1.12.2-1.3.3.jar
millenaire-8.1.2.jar
minerva-library-1.0.13.jar
MJRLegendsLib-1.12.2-1.2.1.jar
MmmMmmMmmMmm-1.12-1.14.jar
MobGrindingUtils-0.3.13.jar
modnametooltip_1.12.2-1.10.1.jar
modularui-2.3.1.jar
More-Planets-1.12.2-2.3.2-GC4.0.5.jar
moremystcraft-1.12.2-1.0.0-sources.jar
MoSpells-1.12.2-1.0.3.jar
MouseTweaks-2.10.1-mc1.12.2.jar
movingelevators-1.3.12-forge-mc1.12.jar
movingworld-1.12-6.353-full.jar
mowziesmobs-1.5.8.jar
multimob-1.0.5.jar
mystcraft-1.12.2-0.13.7.06.jar
mystcraft-jei-1.12.2-1.0.0.jar
mystcraft_info-1.12.2-1.0.5.0.jar
mysticallib-1.12.2-1.13.0.jar
mystlibrary-1.12.2-0.0.3.2.jar
NaturesCompass-1.12.2-1.8.5.jar
NetherEx-1.12.2-2.2.5.jar
NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar
NoMoreRecipeConflict-0.13.jar
Nothirium-1.12.2-0.3.4-beta.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenModsLib-1.12.2-0.12.2.jar
OptiFine_1.12.2_HD_U_G6_pre1.jar
OreLib-1.12.2-3.6.0.1.jar
overloadedarmorbar-1.0.4g.jar
p455w0rdslib-1.12.2-2.3.161.jar
particleculling-1.12.2-v1.4.1.jar
Patchouli-1.0-23.6.jar
persistency-1.2.0.jar
phosphor-1.12.2-0.2.9.3-SNAPSHOT.jar
ProjectIntelligence-1.12.2-1.0.9.28-universal.jar
qsilkspawners-1.1.3.jar
Quark-r1.6-179.jar
randompatches-1.12.2-1.22.1.10.jar
RandomThings-MC1.12.2-4.2.7.4.jar
randomtweaks-1.12.2-2.8.3.1.jar
rats-3.2.14-1.12.2.jar
ReachFix-1.12.2-1.0.8.jar
RebornCore-1.12.2-3.19.5-universal.jar
RebornStorage-1.12.2-3.3.4.1.jar
recycler-3.2.4-1.12.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
redstonepaste-mc1.12-1.7.5.jar
refined_avaritia-1.12.2-2.6.jar
refinedstorage-1.6.16.jar
refinedstorageaddons-0.4.5.jar
RenderLib-1.12.2-1.3.3.jar
Rex's-AdditionalStructures-1.12.x(v.2.5.0).jar
RoguelikeDungeonsFnarEdition-1.12.2-2.4.4.jar
RoughlyEnoughIDs-2.0.6.jar
rsgauges-1.12.2-1.2.6.jar
rsinfinitewireless-1.2.jar
ScalingHealth-1.12.2-1.3.42+147.jar
SilentLib-1.12.2-3.0.14+168.jar
SimplyJetpacks2-1.12.2-2.2.20.0.jar
SmoothFont-mc1.12.2-2.1.4.jar
SoundFilters-0.12.1_for_1.12.jar
SpellBundle-1.12.2-1.1.4.jar
startuptimer-1.0.1.jar
SteveKunG's-Lib-mc1.12.2-v1.3.0.jar
storagecabinet-1.2.0.jar
StorageDrawers-1.12.2-5.4.2.jar
supermartijn642configlib-1.1.6-forge-mc1.12.jar
supermartijn642corelib-1.1.7-forge-mc1.12.jar
tc6aspects4jei-0.0.2a.jar
TConstruct-1.12.2-2.13.0.183.jar
terracartreloaded-1.12.2-1.2.3.jar
tesla-core-lib-1.12.2-1.0.18.jar
TFSpellPack-1.1.0-MC1.12.2.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
thaumic-one-probe-1.12.2-1.0.0.jar
ThaumicAdditions-1.12.2-12.7.8.jar
ThaumicAugmentation-1.12.2-2.1.11.jar
thaumicbases-3.5.230.0.jar
ThaumicInventoryScanning_1.12.2-2.0.10.jar
ThaumicJEI-1.12.2-1.6.0-27.jar
thaumicperiphery-0.3.1.jar
thaumicspeedup-4.0.jar
thaumictinkerer-1.12.2-5.0-620a0c5.jar
thaumicwonders-1.8.2.jar
thaumtweaks-0.3.5.3.jar
TheBetweenlands-3.9.6-universal.jar
TheOneProbe-CE-1.12-1.2.4.jar
TickCentral-3.2.jar
tinkersaether-1.4.1.jar
tinkersjei-1.2.jar
TinkerToolLeveling-1.12.2-1.1.0.jar
topaddons-1.12.2-1.13.0.jar
torohealth-1.12.2-11.jar
TrashSlot_1.12.2-8.4.10.jar
TravelersBackpack-1.12.2-1.0.35.jar
Treasure2-mc1.12.2-f14.23.5.2859-v2.2.0.jar
Treasure2Atum2LP-mc1.12.2-f14.23.5.2859-v2.0.0.jar
Treasure2MoCreaturesLP-mc1.12.2-f14.23.5.2859-v2.0.0.jar
Treasure2TwilightForestLP-mc1.12.2-f14.23.5.2859-v2.0.0.jar
Treasure2WizardryLP-mc1.12.2-f14.23.5.2859-v2.0.0.jar
twilightforest-1.12.2-3.11.1021-universal.jar
u_team_core-1.12.2-2.2.5.255.jar
UniversalTweaks-1.12.2-1.9.0.jar
VeinMiner-1.12-0.38.2.647_b31535a.jar
vintagefix-0.3.3.jar
Waystones_1.12.2-4.1.0.jar
whatloomsahead-1.12.2-1.2.2.jar
WizardryNecromancersDelight-1.12.2-1.0.5.jar
WizardryUtils-1.12.2-1.1.4.jar
Xaeros_Minimap_23.9.1_Forge_1.12.jar
XaerosWorldMap_1.37.1_Forge_1.12.jar
XPFromHarvest-1.12.2-1.2.0.jar
yoyos_1.12.2-1.3.3.25.jar

**Comment by Routersan** [comment]
I found the source of the problem. If you're wondering, it was _topaddons_

**Comment by ukmojb** [comment]
![屏幕截图 2023-12-09 231128](https://github.com/ukmojb/The-One-Probe-Community-Edition/assets/105061290/0770ed03-15bd-429c-a569-55307f3d4787)
I found that this is a bug in the original top, but I will try to fix it

> I found the source of the problem. If you're wondering, it was _topaddons_

**Comment by ukmojb** [comment]
> I found the source of the problem. If you're wondering, it was _topaddons_

[Fix Topaddon's Architecturecraft Modle-1.0.zip](https://github.com/ukmojb/The-One-Probe-Community-Edition/files/13626641/Fix.Topaddon.s.Architecturecraft.Modle-1.0.zip)
I used the mixin to fix bug(In fact you should feed the problem back to topaddon because that's its problem)

**Comment by 1terrain** [comment]
thank you for the fix ukmojb
