### ISSUE TITLE
Payload server kick when looking at certain entities

### ISSUE THREAD

**Issue by Sereath** [ukmojb/The-One-Probe-Community-Edition#9]
I get:
![image](https://github.com/ukmojb/The-One-Probe-Community-Edition/assets/54506307/8576b7a4-e508-4ae9-9dca-163323c4eae1)

**log:**
https://gist.github.com/Sereath/b3ea49e28c0249a015763c5a5d8fab55

When looking at an entity with many debuffs on it (picture taken while using the original Probe mod):
![image](https://github.com/ukmojb/The-One-Probe-Community-Edition/assets/54506307/affe72be-4d83-4056-bb92-415b2a4d493a)

With The One Probe Community Edition:
https://youtu.be/agohq3R-iYQ

With the original The One Probe, no server kick:
https://youtu.be/j0tphcKW_gY

**Comment by ukmojb** [comment]
How many versions?

**Comment by Sereath** [comment]
TheOneProbe-CE-1.12-1.2.4

**Comment by ukmojb** [comment]
![2023-12-16_10 51 43](https://github.com/ukmojb/The-One-Probe-Community-Edition/assets/105061290/269a46c6-fb70-4849-8b4c-73948214a382)
Sorry, there were no problems with the server in my tests.)))) Why don't you try an older version? I also found that I do not know why the potion effect of the entity needs to be re-entered into the archive to display, maybe I need to continue to find the problem later

**Comment by ukmojb** [comment]
One more question: Are there any crash reports?(.minecraft/crash-reports)

**Comment by Sereath** [comment]
No crashes, only the client log I uploaded above. 
The server didn't have anything either.

It doesn't show but I'm also certain that the dummy from our server world has debuffs from tinkers/tinkers evolution on it.
I know this is a painful thing to debug, so I don't expect any more answers right now. Mostly just a heads up, reference for future problems.

**Comment by Sereath** [comment]
Managed to capture it with a Cyclic Monster Ball:
![image](https://github.com/ukmojb/The-One-Probe-Community-Edition/assets/54506307/6b0d7a83-dbac-441c-84e5-601b400cf571)

And I also have a backup of the world with that dummy, just in case.

**Comment by ukmojb** [comment]
1.2.6 fixed
